import type { TemplateData } from "../templates";

export const TEMPLATES_ES: Record<string, TemplateData> = {
  "employee-schedule-builder": {
    slug: "employee-schedule-builder",
    title: "Creador de horarios de empleados",
    description:
      "Creador gratuito de horarios de empleados para gerentes. Crear y compartir horarios de trabajo con su equipo en minutos.",
    longDescription:
      "La gestión de los horarios de los empleados no tiene que ser complicada. Nuestro Creador de horarios gratuitos para empleados ayuda a los gerentes y propietarios de negocios a crear, organizar y compartir horarios de trabajo en minutos. \n\nYa sea que esté administrando una tienda minorista, restaurante, centro de atención médica o cualquier negocio con trabajadores por turnos, esta herramienta facilita la programación. Establezca turnos de mañana, tarde y noche, asigne a los empleados a horarios específicos y asegure una cobertura adecuada durante toda la semana.\n\nLos principales beneficios incluyen la programación de arrastrar y soltar, los cambios codificados por colores para una fácil visualización y la capacidad de exportar su programación como una imagen para compartir con su equipo. Ya no hay dolores de cabeza de hojas de cálculo o conflictos de programación.",
    category: "Negocios",
    icon: "Briefcase",
    settings: {
      weekStartsOnSunday: false,
      use12HourFormat: true,
      workingHoursStart: 6,
      workingHoursEnd: 22,
      timeIncrement: 30,
      showDates: false,
    },
    events: [
      {
        title: "John - Mañana",
        description: "Front Desk",
        day: 1,
        startHour: 6,
        startMinute: 0,
        endHour: 14,
        endMinute: 0,
        color: "blue",
        icon: "Briefcase",
      },
      {
        title: "Sara - tarde",
        description: "Front Desk",
        day: 1,
        startHour: 14,
        startMinute: 0,
        endHour: 22,
        endMinute: 0,
        color: "green",
        icon: "User",
      },
      {
        title: "Mike - Mañana",
        description: "Warehouse",
        day: 2,
        startHour: 6,
        startMinute: 0,
        endHour: 14,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Lisa - Por la tarde",
        description: "Warehouse",
        day: 2,
        startHour: 14,
        startMinute: 0,
        endHour: 22,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "John - Mañana",
        description: "Front Desk",
        day: 3,
        startHour: 6,
        startMinute: 0,
        endHour: 14,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Mike - tarde",
        description: "Front Desk",
        day: 3,
        startHour: 14,
        startMinute: 0,
        endHour: 22,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Sara - Mañana",
        description: "Servicio al Cliente",
        day: 4,
        startHour: 6,
        startMinute: 0,
        endHour: 14,
        endMinute: 0,
        color: "green",
      },
      {
        title: "Lisa - Por la tarde",
        description: "Servicio al Cliente",
        day: 4,
        startHour: 14,
        startMinute: 0,
        endHour: 22,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Reunión de todo el personal",
        description: "Sala de conferencias",
        day: 5,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "red",
      },
      {
        title: "John - Día del Cambio",
        description: "Front Desk",
        day: 5,
        startHour: 10,
        startMinute: 0,
        endHour: 18,
        endMinute: 0,
        color: "blue",
      },
    ],
  },
  "college-class-schedule-builder": {
    slug: "college-class-schedule-builder",
    title: "Construcción de horarios de clases universitarias",
    description:
      "Creador de horarios de clases universitarias gratuitas para estudiantes. Planifique su semestre con nuestro planificador visual fácil de usar.",
    longDescription:
      "La planificación de su semestre universitario se ha vuelto más fácil. Nuestro Creador de Horarios de Clases Gratuitos ayuda a los estudiantes a organizar sus clases, sesiones de estudio y actividades del campus en un horario visual.\n\nDiseñada específicamente para estudiantes universitarios y universitarios, esta herramienta cuenta con una vista de lunes a viernes con incrementos de tiempo de 15 minutos, lo que la hace perfecta para encajar en esas conferencias y sesiones de laboratorio.\n\nUtilice la codificación por color para diferenciar entre los temas, agregue números de habitación y nombres de profesores en la descripción e identifique brechas en su horario para el tiempo de estudio o trabajos en el campus. Exporta tu horario para compartir con tus compañeros de cuarto o imprime para la pared de tu dormitorio.",
    category: "Educación",
    icon: "GraduationCap",
    settings: {
      weekStartsOnSunday: false,
      use12HourFormat: true,
      workingHoursStart: 8,
      workingHoursEnd: 18,
      timeIncrement: 15,
      showDates: true,
    },
    events: [
      {
        title: "Cálculo 101",
        description: "Sala 201 - Prof. Smith",
        day: 1,
        startHour: 8,
        startMinute: 0,
        endHour: 9,
        endMinute: 30,
        color: "blue",
        icon: "Calculator",
      },
      {
        title: "Laboratorio de física",
        description: "Ciencias 305",
        day: 1,
        startHour: 10,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "green",
        icon: "FlaskConical",
      },
      {
        title: "Almuerzo Break",
        description: "Centro Estudiantil",
        day: 1,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "yellow",
        icon: "Coffee",
      },
      {
        title: "Inglés Composición",
        description: "Humanidades 102",
        day: 1,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 30,
        color: "purple",
        icon: "PenTool",
      },
      {
        title: "Química",
        description: "Ciencias 201",
        day: 2,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "orange",
      },
      {
        title: "Grupo de estudio",
        description: "Biblioteca",
        day: 2,
        startHour: 11,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "teal",
      },
      {
        title: "Almuerzo Break",
        description: "Centro Estudiantil",
        day: 2,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Historia",
        description: "Humanidad 305",
        day: 2,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 30,
        color: "red",
      },
      {
        title: "Cálculo 101",
        description: "Sala 201 - Prof. Smith",
        day: 3,
        startHour: 8,
        startMinute: 0,
        endHour: 9,
        endMinute: 30,
        color: "blue",
      },
      {
        title: "Ciencia informática",
        description: "Edificio Tecnológico 101",
        day: 3,
        startHour: 10,
        startMinute: 0,
        endHour: 11,
        endMinute: 30,
        color: "pink",
      },
      {
        title: "Almuerzo Break",
        description: "Centro Estudiantil",
        day: 3,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Oficina Horas",
        description: "Oficina del Prof. Smith",
        day: 3,
        startHour: 15,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Laboratorio de Química",
        description: "Edificio Científico 310",
        day: 4,
        startHour: 9,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Almuerzo Break",
        description: "Centro Estudiantil",
        day: 4,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Inglés Composición",
        description: "Humanidades 102",
        day: 4,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 30,
        color: "purple",
      },
      {
        title: "Cálculo 101",
        description: "Sala 201 - Prof. Smith",
        day: 5,
        startHour: 8,
        startMinute: 0,
        endHour: 9,
        endMinute: 30,
        color: "blue",
      },
      {
        title: "Lección física",
        description: "Ciencia del edificio 101",
        day: 5,
        startHour: 10,
        startMinute: 0,
        endHour: 11,
        endMinute: 30,
        color: "green",
      },
    ],
  },
  "workout-schedule-builder": {
    slug: "workout-schedule-builder",
    title: "Construcción de horarios de entrenamiento",
    description:
      "Creador de horarios de entrenamiento gratuitos para los entusiastas del fitness. Planifique su rutina semanal de gimnasio con nuestro planificador visual.",
    longDescription:
      "Lleve su viaje de fitness al siguiente nivel con nuestro Creador de horarios de entrenamiento gratuitos. Ya sea que esté siguiendo una rutina de empuje y tirar de piernas, entrenando para un maratón o simplemente tratando de mantenerse activo, este planificador visual le ayuda a organizar sus entrenamientos para la semana.\n\nDiseñada con los entusiastas del fitness en mente, esta herramienta le permite programar grupos musculares específicos, sesiones de cardio, días de descanso y tiempos de preparación de comidas. Código de color de sus entrenamientos para distinguir entre el día del pecho, el día de la espalda, el día de las piernas y las sesiones de cardio.\n\nPerfecto para principiantes que crean su primer plan de entrenamiento o para atletas experimentados que mantienen horarios de entrenamiento complejos. Exporta tu plan y guárdalo en tu teléfono para una referencia rápida en el gimnasio.",
    category: "Personal",
    icon: "Dumbbell",
    settings: {
      weekStartsOnSunday: true,
      use12HourFormat: true,
      workingHoursStart: 5,
      workingHoursEnd: 21,
      timeIncrement: 30,
      showDates: false,
    },
    events: [
      {
        title: "Día de descanso",
        description: "Recuperación activa, estiramiento",
        day: 0,
        startHour: 8,
        startMinute: 0,
        endHour: 9,
        endMinute: 0,
        color: "teal",
      },
      {
        title: "Caminar luz",
        description: "30 minutos caminando al aire libre",
        day: 0,
        startHour: 17,
        startMinute: 0,
        endHour: 17,
        endMinute: 30,
        color: "green",
      },
      {
        title: "Chest y Triceps",
        description: "Prensa de banco, dips, pushups",
        day: 1,
        startHour: 6,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "red",
        icon: "Dumbbell",
      },
      {
        title: "Comida de proteínas",
        description: "Nutrición post-entrenamiento",
        day: 1,
        startHour: 8,
        startMinute: 0,
        endHour: 8,
        endMinute: 30,
        color: "yellow",
        icon: "Zap",
      },
      {
        title: "Noche Cardio",
        description: "20 minutos de jog ligero",
        day: 1,
        startHour: 18,
        startMinute: 0,
        endHour: 18,
        endMinute: 30,
        color: "green",
        icon: "Activity",
      },
      {
        title: "De espalda y bíceps",
        description: "Pull-ups, filas, curls",
        day: 2,
        startHour: 6,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "blue",
      },
      {
        title: "Comida de proteínas",
        description: "Nutrición post-entrenamiento",
        day: 2,
        startHour: 8,
        startMinute: 0,
        endHour: 8,
        endMinute: 30,
        color: "yellow",
      },
      {
        title: "Yoga",
        description: "45 minutos de flexibilidad",
        day: 2,
        startHour: 17,
        startMinute: 30,
        endHour: 18,
        endMinute: 15,
        color: "teal",
      },
      {
        title: "Cardio",
        description: "30 minutos de running + HIIT",
        day: 3,
        startHour: 6,
        startMinute: 0,
        endHour: 7,
        endMinute: 0,
        color: "green",
      },
      {
        title: "Stretching",
        description: "15 minutos de flexibilidad",
        day: 3,
        startHour: 7,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Core Workout",
        description: "Abs y Planks",
        day: 3,
        startHour: 18,
        startMinute: 0,
        endHour: 18,
        endMinute: 30,
        color: "purple",
      },
      {
        title: "Piernas y Core",
        description: "Squats, lunges, planchas",
        day: 4,
        startHour: 6,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "purple",
      },
      {
        title: "Comida de proteínas",
        description: "Nutrición post-entrenamiento",
        day: 4,
        startHour: 8,
        startMinute: 0,
        endHour: 8,
        endMinute: 30,
        color: "yellow",
      },
      {
        title: "Recuperación Walk",
        description: "Luz 30 minutos caminando",
        day: 4,
        startHour: 17,
        startMinute: 0,
        endHour: 17,
        endMinute: 30,
        color: "green",
      },
      {
        title: "hombros y brazos",
        description: "OHP, elevaciones laterales",
        day: 5,
        startHour: 6,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "orange",
      },
      {
        title: "Comida de proteínas",
        description: "Nutrición post-entrenamiento",
        day: 5,
        startHour: 8,
        startMinute: 0,
        endHour: 8,
        endMinute: 30,
        color: "yellow",
      },
      {
        title: "Stretch y Foam Roll",
        description: "Sesión de recuperación",
        day: 5,
        startHour: 18,
        startMinute: 0,
        endHour: 18,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Cardio de cuerpo completo",
        description: "Natación o ciclismo",
        day: 6,
        startHour: 8,
        startMinute: 0,
        endHour: 9,
        endMinute: 30,
        color: "green",
      },
      {
        title: "Preparación de comida",
        description: "Prepara las comidas de la semana",
        day: 6,
        startHour: 11,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "pink",
      },
      {
        title: "Actividad Outdoor",
        description: "Hiking o deportes",
        day: 6,
        startHour: 15,
        startMinute: 0,
        endHour: 17,
        endMinute: 0,
        color: "green",
      },
    ],
  },
  "visual-schedule-builder": {
    slug: "visual-schedule-builder",
    title: "Constructor de calendario visual",
    description:
      "Constructor de horarios visuales gratuitos para planificadores creativos. Crear hermosos horarios codificados por colores de un vistazo.",
    longDescription:
      "Transforma tu agenda de una lista aburrida en una hermosa obra maestra visual. Nuestro creador de horarios visuales gratuitos utiliza colores, bloques y diseño intuitivo para ayudarle a ver su semana de un vistazo.\n\nPerfecto para estudiantes visuales, profesionales creativos y cualquier persona que prefiera ver su horario en lugar de leerlo.La interfaz de arrastrar y soltar facilita la organización y reorganización de sus planes, mientras que el sistema de codificación por colores le ayuda a identificar al instante diferentes tipos de actividades.\n\nYa sea que esté planeando un proyecto creativo, gestionando múltiples clientes u organizando su vida personal, este enfoque visual de la programación le ayuda a detectar conflictos, encontrar tiempo libre y mantener el equilibrio en todas las áreas de su vida.",
    category: "Personal",
    icon: "Palette",
    settings: {
      weekStartsOnSunday: true,
      use12HourFormat: true,
      workingHoursStart: 7,
      workingHoursEnd: 20,
      timeIncrement: 30,
      showDates: false,
    },
    events: [
      {
        title: "Trabajo creativo",
        description: "Proyectos de diseño",
        day: 1,
        startHour: 9,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "pink",
      },
      {
        title: "Almuerzo",
        description: "Break",
        day: 1,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Llamadas del cliente",
        description: "Reuniones",
        day: 1,
        startHour: 14,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Tarea de Admin",
        description: "Emails, Planificación",
        day: 2,
        startHour: 9,
        startMinute: 0,
        endHour: 11,
        endMinute: 0,
        color: "teal",
      },
      {
        title: "Fotografía",
        description: "Disparos exterior",
        day: 2,
        startHour: 13,
        startMinute: 0,
        endHour: 17,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Trabajo creativo",
        description: "Ilustración",
        day: 3,
        startHour: 9,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "pink",
      },
      {
        title: "Almuerzo reunión",
        description: "Discusión Cliente",
        day: 3,
        startHour: 12,
        startMinute: 0,
        endHour: 14,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Social Media",
        description: "Creación de contenido",
        day: 3,
        startHour: 15,
        startMinute: 0,
        endHour: 17,
        endMinute: 0,
        color: "green",
      },
      {
        title: "Taller",
        description: "Sesión de enseñanza",
        day: 4,
        startHour: 10,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "red",
      },
      {
        title: "Tiempo personal",
        description: "Autocuidado",
        day: 4,
        startHour: 15,
        startMinute: 0,
        endHour: 17,
        endMinute: 0,
        color: "teal",
      },
      {
        title: "Revisión del proyecto",
        description: "Equipo de sincronización",
        day: 5,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "blue",
      },
      {
        title: "Trabajo creativo",
        description: "Finalización de proyectos",
        day: 5,
        startHour: 11,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "pink",
      },
    ],
  },
  "ai-schedule-builder": {
    slug: "ai-schedule-builder",
    title: "Construcción de calendario ",
    description:
      "Genera un horario semanal personalizado en segundos con AI. Programación inteligente y automatizada adaptada a su productividad, niveles de energía y objetivos.",
    longDescription:
      "Experimenta el futuro de la gestión del tiempo con nuestro creador de horarios de IA. En lugar de empezar con una plantilla rígida, esta herramienta utiliza algoritmos avanzados para ayudarle a generar un plan semanal optimizado desde cero.\n\nSimplemente aplique esta plantilla y nuestro asistente de autocomposición de IA lo guiará a través de la creación de un horario que equilibre el trabajo profundo, el descanso y las prioridades personales. Nuestro sistema inteligente considera las mejores prácticas de productividad, como abordar tareas complejas durante las horas de máxima energía, para crear una rutina que realmente se adhiera.\n\nYa sea que seas un fundador ocupado maximizando la producción, un estudiante que equilibra cargas pesadas de cursos, o cualquier persona que busque recuperar su tiempo, nuestro Generador de Horarios de IA elimina la tarea pesada de planificar tu semana.",
    category: "El AI",
    icon: "Sparkles",
    requiresPro: true,
    settings: {
      weekStartsOnSunday: false,
      use12HourFormat: false,
      workingHoursStart: 8,
      workingHoursEnd: 18,
      timeIncrement: 15,
      showDates: true,
    },
    events: [],
  },
  "work-shift-schedule-builder": {
    slug: "work-shift-schedule-builder",
    title: "Trabajo Shift Schedule Builder",
    description:
      "Creador de horarios de turnos de trabajo gratuitos para gerentes. Construir turnos rotativos para las tripulaciones de la mañana, la tarde y la noche.",
    longDescription:
      "Simplifique su programación de turnos con nuestro generador de horarios de turnos de trabajo gratuito. Diseñado para gerentes, supervisores y propietarios de negocios que necesitan coordinar turnos de trabajo rotativos entre equipos.\n\nYa sea que esté administrando una operación 24 / 7, un restaurante con turnos divididos, una instalación de atención médica con enfermeras rotativas o una planta de fabricación con equipos diurnos y nocturnos, este planificador de turnos visual facilita la organización de la cobertura y la comunicación de los horarios con claridad.\n\nNuestro intuitivo creador de horarios cuenta con turnos codificados por colores para distinguir entre los turnos de la mañana (dia), la tarde (swing) y la noche (cementerio) de un vistazo. La interfaz de arrastrar y soltar le permite asignar rápidamente a los empleados, cambiar turnos y garantizar una cobertura adecuada. Resalta los turnos nocturnos en púrpura para una visibilidad instantánea y exporta tu lista completa para compartir con tu equipo por correo electrónico o imprimirla para la sala de descanso.\n\nDeje de luchar con hojas de cálculo y comience a construir horarios de turnos profesionales en minutos.",
    category: "Negocios",
    icon: "Briefcase",
    settings: {
      weekStartsOnSunday: true,
      use12HourFormat: false,
      workingHoursStart: 0,
      workingHoursEnd: 24,
      timeIncrement: 30,
      showDates: true,
    },
    events: [
      {
        title: "Night Shift - Equipo C",
        description: "Cobertura nocturna",
        day: 0,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Day Shift - Equipo A",
        description: "Mañana tripulación",
        day: 0,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Swing Shift - Equipo B",
        description: "tarde / tarde",
        day: 0,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Night Shift - Equipo C",
        description: "Cambio de cementerio",
        day: 1,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Day Shift - Equipo A",
        description: "Operaciones de la mañana",
        day: 1,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Swing Shift - Equipo B",
        description: "tarde / tarde",
        day: 1,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Night Shift - Equipo A",
        description: "Rotación a las noches",
        day: 2,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Día de cambio - Equipo B",
        description: "Rotación a días",
        day: 2,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Swing Shift - Equipo C",
        description: "Rotación para swing",
        day: 2,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Night Shift - Equipo A",
        description: "Tripulación nocturna",
        day: 3,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Día de cambio - Equipo B",
        description: "Día de la tripulación",
        day: 3,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Swing Shift - Equipo C",
        description: "Noche de tripulación",
        day: 3,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Night Shift - Equipo A",
        description: "Tripulación nocturna",
        day: 4,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Día de cambio - Equipo B",
        description: "Día de la tripulación",
        day: 4,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Reunión de manos",
        description: "Sincronización mensual de equipos",
        day: 4,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "red",
      },
      {
        title: "Swing Shift - Equipo C",
        description: "Noche de tripulación",
        day: 4,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Night Shift - Equipo B",
        description: "Rotación a las noches",
        day: 5,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Day Shift - Equipo C",
        description: "Rotación a días",
        day: 5,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Swing Shift - Equipo A",
        description: "Rotación para swing",
        day: 5,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Night Shift - Equipo B",
        description: "Weekend Noches",
        day: 6,
        startHour: 0,
        startMinute: 0,
        endHour: 8,
        endMinute: 0,
        color: "purple",
      },
      {
        title: "Day Shift - Equipo C",
        description: "Días de fin de semana",
        day: 6,
        startHour: 8,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Swing Shift - Equipo A",
        description: "Noches de fin de semana",
        day: 6,
        startHour: 16,
        startMinute: 0,
        endHour: 24,
        endMinute: 0,
        color: "orange",
      },
    ],
  },
  "homeschool-schedule-builder": {
    slug: "homeschool-schedule-builder",
    title: "Construcción de horarios de Homeschool",
    description:
      "Constructor de horarios de educación en casa gratuito para familias. Diseñe rutinas de aprendizaje flexibles que funcionen para su viaje de educación en casa.",
    longDescription:
      "Cree el horario perfecto de educación en el hogar con nuestro Creador de horarios gratuitos de educación en el hogar, diseñado específicamente para las familias que educan en el hogar. Ya sea que estés enseñando a un niño o administrando varios niveles de grado, este planificador visual te ayuda a organizar las materias, las pausas y las actividades en una rutina semanal equilibrada.\n\nNuestra cálida interfaz familiar facilita la planificación de materias básicas como matemáticas, lectura, ciencias e historia junto con actividades de enriquecimiento como arte, música y educación física. Código de color diferentes temas para una referencia visual rápida, y programa descansos regulares para mantener a sus hijos comprometidos y refrescados.\n\nEl diseño flexible da cabida a varios enfoques de educación en casa, desde la educación clásica estructurada hasta la educación relajada sin escolaridad. Arrastrar y soltar para ajustar los horarios de lección, agregar excursiones y actividades extracurriculares o crear horarios diferentes para cada niño. Exporta tu horario completado para imprimirlo para el espacio de aprendizaje o comparta digitalmente con grupos cooperativos y tutores.\n\nPerfecto para nuevas familias de educación en casa que comienzan su viaje o educadores experimentados que refinan su rutina. Cree un horario que funcione para su familia, no un enfoque de aula de tamaño único para todos.",
    category: "Educación",
    icon: "Home",
    settings: {
      weekStartsOnSunday: false,
      use12HourFormat: true,
      workingHoursStart: 8,
      workingHoursEnd: 16,
      timeIncrement: 15,
      showDates: false,
    },
    events: [
      {
        title: "Círculo matutino",
        description: "Calendario, tiempo, lectura en voz alta",
        day: 1,
        startHour: 8,
        startMinute: 30,
        endHour: 9,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Matemáticas",
        description: "Lección + Problemas de práctica",
        day: 1,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Snack Break",
        description: "Tiempo de snack saludable",
        day: 1,
        startHour: 10,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Lectura",
        description: "Fonología / Literatura",
        day: 1,
        startHour: 10,
        startMinute: 30,
        endHour: 11,
        endMinute: 15,
        color: "green",
      },
      {
        title: "Ciencia",
        description: "Experimentos Hands-on",
        day: 1,
        startHour: 11,
        startMinute: 15,
        endHour: 12,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Almuerzo y juego libre",
        description: "Almuerzo en familia",
        day: 1,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "pink",
      },
      {
        title: "Escribiendo",
        description: "Diario / escritura a mano",
        day: 1,
        startHour: 13,
        startMinute: 0,
        endHour: 13,
        endMinute: 45,
        color: "purple",
      },
      {
        title: "Art",
        description: "Proyectos creativos",
        day: 1,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "red",
      },
      {
        title: "Círculo matutino",
        description: "La rutina diaria",
        day: 2,
        startHour: 8,
        startMinute: 30,
        endHour: 9,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Matemáticas",
        description: "Nuevos conceptos + revisión",
        day: 2,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Snack Break",
        description: "Movimiento Break",
        day: 2,
        startHour: 10,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Lectura",
        description: "Tiempo de lectura silenciosa",
        day: 2,
        startHour: 10,
        startMinute: 30,
        endHour: 11,
        endMinute: 15,
        color: "green",
      },
      {
        title: "Historia",
        description: "Historia del mundo",
        day: 2,
        startHour: 11,
        startMinute: 15,
        endHour: 12,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Almuerzo y juego libre",
        description: "Tiempo exterior",
        day: 2,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "pink",
      },
      {
        title: "Música",
        description: "Práctica del instrumento",
        day: 2,
        startHour: 13,
        startMinute: 0,
        endHour: 13,
        endMinute: 45,
        color: "purple",
      },
      {
        title: "PE / Deportes",
        description: "Actividad física",
        day: 2,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "red",
      },
      {
        title: "Círculo matutino",
        description: "Memorización de poesía",
        day: 3,
        startHour: 8,
        startMinute: 30,
        endHour: 9,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Matemáticas",
        description: "Juegos + Hojas de trabajo",
        day: 3,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Snack Break",
        description: "Esquina de lectura",
        day: 3,
        startHour: 10,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Lectura",
        description: "Libro Discusión",
        day: 3,
        startHour: 10,
        startMinute: 30,
        endHour: 11,
        endMinute: 15,
        color: "green",
      },
      {
        title: "Estudio Naturaleza",
        description: "Exploración exterior",
        day: 3,
        startHour: 11,
        startMinute: 15,
        endHour: 12,
        endMinute: 30,
        color: "orange",
      },
      {
        title: "Almuerzo y juego libre",
        description: "Picnic si el tiempo lo permite",
        day: 3,
        startHour: 12,
        startMinute: 30,
        endHour: 13,
        endMinute: 30,
        color: "pink",
      },
      {
        title: "Biblioteca Visita",
        description: "Viajes semanales a la biblioteca",
        day: 3,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 30,
        color: "purple",
      },
      {
        title: "Círculo matutino",
        description: "Actividades Calendario",
        day: 4,
        startHour: 8,
        startMinute: 30,
        endHour: 9,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Matemáticas",
        description: "Problemas de resolución",
        day: 4,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Snack Break",
        description: "El Stretch Break",
        day: 4,
        startHour: 10,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Lectura",
        description: "Leer en voz alta juntos",
        day: 4,
        startHour: 10,
        startMinute: 30,
        endHour: 11,
        endMinute: 15,
        color: "green",
      },
      {
        title: "Geografía",
        description: "Habilidades de mapeo + Cultura",
        day: 4,
        startHour: 11,
        startMinute: 15,
        endHour: 12,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Almuerzo y juego libre",
        description: "Juegos indoor",
        day: 4,
        startHour: 12,
        startMinute: 0,
        endHour: 13,
        endMinute: 0,
        color: "pink",
      },
      {
        title: "Escribiendo",
        description: "Escritura creativa",
        day: 4,
        startHour: 13,
        startMinute: 0,
        endHour: 13,
        endMinute: 45,
        color: "purple",
      },
      {
        title: "Proyecto Craft",
        description: "Hands-on haciendo",
        day: 4,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "red",
      },
      {
        title: "Círculo matutino",
        description: "Semana Revisión",
        day: 5,
        startHour: 8,
        startMinute: 30,
        endHour: 9,
        endMinute: 0,
        color: "yellow",
      },
      {
        title: "Matemáticas",
        description: "Juegos de matemáticas / reseña",
        day: 5,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "blue",
      },
      {
        title: "Snack Break",
        description: "Snack de celebración",
        day: 5,
        startHour: 10,
        startMinute: 0,
        endHour: 10,
        endMinute: 30,
        color: "teal",
      },
      {
        title: "Lectura",
        description: "Libre elección de lectura",
        day: 5,
        startHour: 10,
        startMinute: 30,
        endHour: 11,
        endMinute: 15,
        color: "green",
      },
      {
        title: "Show y Tell",
        description: "Compartir lo que aprendimos",
        day: 5,
        startHour: 11,
        startMinute: 15,
        endHour: 12,
        endMinute: 0,
        color: "orange",
      },
      {
        title: "Viaje de campo / Co-op",
        description: "Actividades del grupo",
        day: 5,
        startHour: 12,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "pink",
      },
    ],
  },
  "construction-schedule-builder": {
    slug: "construction-schedule-builder",
    title: "Calendario de construcción Builder",
    description:
      "Constructor profesional de cronogramas de construcción para contratistas y gerentes de proyectos. Planifique plazos, rastree hitos y administre equipos de manera eficiente.",
    longDescription:
      "Domina sus proyectos de construcción con nuestro profesional Constructor de horarios de construcción. Diseñado específicamente para contratistas generales, gerentes de sitio y equipos de construcción que necesitan una gestión robusta de líneas de tiempo sin la complejidad del software heredado.\n\nPlanifique cada fase de su construcción, desde la preparación del sitio hasta el recorrido final. Nuestro enfoque visual de estilo Gantt le ayuda a identificar rutas críticas, gestionar las entregas de la tripulación y garantizar que los materiales lleguen exactamente cuando se necesiten.\n\nLas características clave incluyen el seguimiento basado en fases (demolición, fundación, enmarcado, servicios públicos), asignación de recursos y monitoreo de hitos. La vista de línea de tiempo intuitiva le permite detectar posibles retrasos temprano, coordinar a los subcontratistas de manera efectiva y mantener a los clientes actualizados con informes de progreso profesionales.\n\nPerfecto para edificios residenciales, proyectos de renovación y ajustes comerciales. Tome el control de su sitio de trabajo con un horario que trabaje tan duro como su equipo.",
    category: "Negocios",
    icon: "HardHat",
    requiresPro: true,
    settings: {
      weekStartsOnSunday: false,
      use12HourFormat: true,
      workingHoursStart: 6,
      workingHoursEnd: 18,
      timeIncrement: 60,
      showDates: true,
    },
    events: [
      {
        title: "Preparación del sitio",
        description: "Excavación y nivelación",
        day: 1,
        startHour: 6,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "orange",
        icon: "TrendingUp",
      },
      {
        title: "Preparación del sitio",
        description: "Excavación y nivelación",
        day: 2,
        startHour: 6,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "orange",
        icon: "TrendingUp",
      },
      {
        title: "Formularios de fundación",
        description: "Establecer formas concretas",
        day: 3,
        startHour: 7,
        startMinute: 0,
        endHour: 17,
        endMinute: 0,
        color: "teal",
        icon: "Maximize",
      },
      {
        title: "Fundación para",
        description: "Llegada del camión de concreto",
        day: 4,
        startHour: 7,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "teal",
        icon: "Maximize",
      },
      {
        title: "Período de curación",
        description: "Sin tráfico pesado",
        day: 5,
        startHour: 6,
        startMinute: 0,
        endHour: 18,
        endMinute: 0,
        color: "yellow",
        icon: "Clock",
      },
      {
        title: "Entrega de materiales",
        description: "Paquete de madera Drop",
        day: 4,
        startHour: 13,
        startMinute: 0,
        endHour: 15,
        endMinute: 0,
        color: "blue",
        icon: "Truck",
      },
      {
        title: "Sitio Reunión",
        description: "Propietario Walkthrough",
        day: 5,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "red",
        icon: "Users",
      },
      {
        title: "Verificación de seguridad del sitio",
        description: "Verificación semanal del perímetro",
        day: 6,
        startHour: 9,
        startMinute: 0,
        endHour: 10,
        endMinute: 0,
        color: "purple",
        icon: "Shield",
      },
    ],
  },
  "cleaning-schedule-builder": {
    slug: "cleaning-schedule-builder",
    title: "Limpieza del calendario de construcción",
    description:
      "Creador de horarios de limpieza imprimible gratuito para hogares. Cree tablas de tareas y rutinas de limpieza para su familia o compañeros de cuarto.",
    longDescription:
      "Mantenga su hogar limpio con nuestro generador de horarios de limpieza gratuitos. Ya sea que seas un padre ocupado administrando las tareas domésticas, compañeros de cuarto que dividen las tareas de limpieza, o cualquier persona que quiera mantenerse al tanto de las tareas domésticas, este planificador visual hace que la limpieza sea manejable y organizada.\n\nNuestro generador de horarios de estilo de lista de verificación le ayuda a descomponer las tareas de limpieza en rutinas diarias, semanales y mensuales. Asigne tareas específicas a diferentes días, rote las responsabilidades entre los miembros del hogar y nunca se olvide de esos trabajos de limpieza profunda que son fáciles de perder.\n\nTareas con código de color por habitación (cocina, baño, dormitorio, sala de estar) o por persona para situaciones de vida compartida. El formato visual facilita ver quién es responsable de qué y cuándo. Exporta tu programa de limpieza como una lista de verificación imprimible para colgar en el refrigerador o compartir digitalmente con tus compañeros de cuarto.\n\nPerfecto para establecer rutinas de limpieza, enseñar responsabilidades a los niños, coordinarse con un servicio de limpieza o mantener un espacio de vida tranquilo y libre de desorden.¡Un hogar limpio comienza con un buen plan!",
    category: "Personal",
    icon: "SprayCan",
    settings: {
      weekStartsOnSunday: true,
      use12HourFormat: true,
      workingHoursStart: 7,
      workingHoursEnd: 21,
      timeIncrement: 30,
      showDates: false,
    },
    events: [
      {
        title: "Semanal Lavandería",
        description: "Lavar, secar, doblar toda la ropa",
        day: 0,
        startHour: 9,
        startMinute: 0,
        endHour: 11,
        endMinute: 0,
        color: "blue",
        icon: "WashingMachine",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Cambio de sábanas",
        description: "Todos los dormitorios",
        day: 0,
        startHour: 11,
        startMinute: 0,
        endHour: 12,
        endMinute: 0,
        color: "purple",
        icon: "Bed",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Preparación de comidas y limpieza profunda de cocina",
        description: "Limpiar los electrodomésticos, organizar el refrigerador",
        day: 0,
        startHour: 14,
        startMinute: 0,
        endHour: 16,
        endMinute: 0,
        color: "green",
        icon: "ChefHat",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Mañana Tidy",
        description: "Hacer camas, pick-up rápido",
        day: 1,
        startHour: 7,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "yellow",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Cocina limpia",
        description: "Platos, contadores de limpieza, barrido",
        day: 1,
        startHour: 19,
        startMinute: 0,
        endHour: 19,
        endMinute: 30,
        color: "green",
        icon: "Utensils",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Sacar la basura",
        description: "Todas las habitaciones",
        day: 1,
        startHour: 20,
        startMinute: 0,
        endHour: 20,
        endMinute: 30,
        color: "red",
        icon: "Trash2",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Mañana Tidy",
        description: "Hacer camas, pick-up rápido",
        day: 2,
        startHour: 7,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "yellow",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Baño limpio",
        description: "Scrub inodoro, fregadero, espejo",
        day: 2,
        startHour: 19,
        startMinute: 0,
        endHour: 19,
        endMinute: 45,
        color: "teal",
        icon: "Bath",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Vacuum Living Room",
        description: "Suelos y alfombras",
        day: 2,
        startHour: 20,
        startMinute: 0,
        endHour: 20,
        endMinute: 30,
        color: "orange",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Mañana Tidy",
        description: "Hacer camas, pick-up rápido",
        day: 3,
        startHour: 7,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "yellow",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Cocina limpia",
        description: "Platos, contadores de limpieza",
        day: 3,
        startHour: 19,
        startMinute: 0,
        endHour: 19,
        endMinute: 30,
        color: "green",
        icon: "Utensils",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Superficies de polvo",
        description: "Sala de estar y dormitorios",
        day: 3,
        startHour: 20,
        startMinute: 0,
        endHour: 20,
        endMinute: 30,
        color: "pink",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Mañana Tidy",
        description: "Hacer camas, pick-up rápido",
        day: 4,
        startHour: 7,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "yellow",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Mop piso",
        description: "Cocina y baño",
        day: 4,
        startHour: 19,
        startMinute: 0,
        endHour: 19,
        endMinute: 45,
        color: "blue",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Wipe aparatos",
        description: "Microondas, estufas",
        day: 4,
        startHour: 20,
        startMinute: 0,
        endHour: 20,
        endMinute: 30,
        color: "green",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Mañana Tidy",
        description: "Hacer camas, pick-up rápido",
        day: 5,
        startHour: 7,
        startMinute: 0,
        endHour: 7,
        endMinute: 30,
        color: "yellow",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Rápido limpieza de baño",
        description: "Sink y espejo",
        day: 5,
        startHour: 19,
        startMinute: 0,
        endHour: 19,
        endMinute: 30,
        color: "teal",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Habitaciones Vacuum",
        description: "Todos los pisos dormitorios",
        day: 5,
        startHour: 19,
        startMinute: 30,
        endHour: 20,
        endMinute: 0,
        color: "orange",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Sacar la basura",
        description: "Día de la Basura Prep",
        day: 5,
        startHour: 20,
        startMinute: 0,
        endHour: 20,
        endMinute: 30,
        color: "red",
        icon: "Trash2",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Tarea de Deep Clean",
        description: "Rotar: ventanas, tablas base, etc.",
        day: 6,
        startHour: 10,
        startMinute: 0,
        endHour: 11,
        endMinute: 30,
        color: "purple",
        icon: "Sparkles",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Organizar y Declutter",
        description: "Una habitación enfocada",
        day: 6,
        startHour: 14,
        startMinute: 0,
        endHour: 15,
        endMinute: 30,
        color: "pink",
        icon: "FolderOpen",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
      {
        title: "Comestibles y Restock",
        description: "Suministros de limpieza Check",
        day: 6,
        startHour: 16,
        startMinute: 0,
        endHour: 17,
        endMinute: 0,
        color: "blue",
        icon: "ShoppingCart",
        task: {
          isCheckable: true,
          isCompleted: false,
        },
      },
    ],
  },
};
