"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { PageLayout } from "@/components/PageLayout";
import Link from "next/link";;
import { Briefcase, GraduationCap, Dumbbell, Palette, Sparkles, Crown, ChevronLeft, ChevronRight, Search, Home, SprayCan, HardHat } from "lucide-react";
import { getAllTemplates } from "@/lib/templates";
import { CategoryFilter } from "@/components/CategoryFilter";
import { FAQSection } from "@/components/FAQSection";
import { PageHero } from "@/components/PageHero";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import { Breadcrumb } from "@/components/Breadcrumb";

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
    Briefcase,
    GraduationCap,
    Dumbbell,
    Palette,
    Sparkles,
    Home,
    SprayCan,
    HardHat,
};

const TEMPLATES_PER_PAGE = 18;
const templatesFAQs = [
    {
        question: "Are these templates really free?",
        answer: "Most of our schedule templates are free to use; you can preview, customize, and export your schedule for free. A few schedule templates, such as those generated by AI, require a professional subscription."
    },
    {
        question: "How do I use a template?",
        answer: "Simply click on any template to preview it, then click 'Use This Template' to load it into the editor. From there, you can customize colors, times, labels, and add or remove events to match your needs."
    },
    {
        question: "Can I customize the templates?",
        answer: "Absolutely! Once you load a template into the editor, you have full control to modify every aspect - change event times, colors, titles, add new events, or delete existing ones. The templates are just starting points."
    },
    {
        question: "What export formats are available?",
        answer: "Free users can export schedules as PNG or JPG images (with watermark). Pro users get access to watermark-free exports, PDF format for high-quality printing, and CSV format for data analysis."
    },
    {
        question: "Will my schedule be saved?",
        answer: "Your schedule is automatically saved in your browser's local storage. Pro users also get cloud sync, which allows you to access your schedules from any device."
    }
];

export default function TemplatesPage() {
    const router = useRouter();
    const allTemplates = getAllTemplates();
    const [activeCategory, setActiveCategory] = useState("All");
    const [currentPage, setCurrentPage] = useState(1);
    const [searchQuery, setSearchQuery] = useState("");

    // Get unique categories from templates
    const categories = ["All", ...Array.from(new Set(allTemplates.map(t => t.category)))];

    // Filter templates by category and search query
    const filteredTemplates = allTemplates.filter(t => {
        const matchesCategory = activeCategory === "All" || t.category === activeCategory;
        const matchesSearch = searchQuery.trim() === "" ||
            t.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
            t.description.toLowerCase().includes(searchQuery.toLowerCase());
        return matchesCategory && matchesSearch;
    });

    // Pagination logic
    const totalPages = Math.ceil(filteredTemplates.length / TEMPLATES_PER_PAGE);
    const startIndex = (currentPage - 1) * TEMPLATES_PER_PAGE;
    const paginatedTemplates = filteredTemplates.slice(startIndex, startIndex + TEMPLATES_PER_PAGE);

    const handleCategoryChange = (category: string) => {
        setActiveCategory(category);
        setCurrentPage(1);
    };

    const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setSearchQuery(e.target.value);
        setCurrentPage(1);
    };

    const handlePageChange = (page: number) => {
        if (page >= 1 && page <= totalPages) {
            setCurrentPage(page);
            window.scrollTo({ top: 200, behavior: 'smooth' });
        }
    };

    // Generate page numbers to display
    const getPageNumbers = () => {
        const pages: (number | string)[] = [];
        if (totalPages <= 5) {
            for (let i = 1; i <= totalPages; i++) {
                pages.push(i);
            }
        } else {
            if (currentPage <= 3) {
                pages.push(1, 2, 3, '...', totalPages);
            } else if (currentPage >= totalPages - 2) {
                pages.push(1, '...', totalPages - 2, totalPages - 1, totalPages);
            } else {
                pages.push(1, '...', currentPage, '...', totalPages);
            }
        }
        return pages;
    };

    // FAQ Schema for SEO
    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": templatesFAQs.map((faq) => ({
            "@type": "Question",
            "name": faq.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer,
            },
        })),
    };

    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
            />
            <PageLayout>
                {/* Breadcrumb Navigation */}
                <div className="container mx-auto px-4 max-w-6xl mb-4">
                    <Breadcrumb items={[
                        { label: "Home", href: "/" },
                        { label: "Templates" }
                    ]} />
                </div>

                {/* Hero Section */}
                <PageHero
                    title="Schedule Templates"
                    description="Get started quickly with professionally designed templates. Choose one that fits your needs."
                />

                {/* Search Box */}
                <div className="container mx-auto px-4 max-w-6xl mb-8">
                    <div className="relative max-w-md mx-auto">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                        <Input
                            type="text"
                            placeholder="Search templates by keyword..."
                            value={searchQuery}
                            onChange={handleSearchChange}
                            className="pl-10 pr-10"
                        />
                        {searchQuery && (
                            <button
                                onClick={() => { setSearchQuery(""); setCurrentPage(1); }}
                                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                                aria-label="Clear search"
                            >
                                ✕
                            </button>
                        )}
                    </div>
                </div>

                {/* Category Filter */}
                <div className="container mx-auto px-4 mb-8">
                    <CategoryFilter
                        categories={categories}
                        activeCategory={activeCategory}
                        onCategoryChange={handleCategoryChange}
                    />
                </div>

                {/* Templates Grid */}
                <div className="container mx-auto px-4 max-w-6xl">
                    {paginatedTemplates.length > 0 ? (
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                            {paginatedTemplates.map((template) => {
                                const Icon = template.icon ? iconMap[template.icon] : Briefcase;
                                return (
                                    <Link
                                        key={template.slug}
                                        href={`/templates/${template.slug}`}
                                        className="group bg-white rounded-xl border border-gray-100 p-6 shadow-sm hover:shadow-lg hover:border-blue-200 transition-all duration-200 relative h-full flex flex-col"
                                    >
                                        {/* Pro Badge */}
                                        {template.requiresPro && (
                                            <div className="absolute top-3 right-3">
                                                <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[10px] font-semibold bg-gradient-to-r from-amber-400 to-orange-500 text-white">
                                                    <Crown className="size-2.5" />
                                                    PRO
                                                </span>
                                            </div>
                                        )}
                                        <div className="flex items-start gap-4 flex-1">
                                            <div className="p-3 bg-blue-50 rounded-lg group-hover:bg-blue-100 transition-colors shrink-0 mt-1">
                                                <Icon className="size-6 text-blue-600" />
                                            </div>
                                            <div className="flex-1 min-w-0">
                                                <span className="text-xs font-medium text-blue-600 uppercase tracking-wide">
                                                    {template.category}
                                                </span>
                                                <h3 className="text-lg font-semibold text-gray-900 mt-1 group-hover:text-blue-600 transition-colors line-clamp-1">
                                                    {template.title}
                                                </h3>
                                                <p className="text-sm text-gray-500 mt-2 line-clamp-2">
                                                    {template.description}
                                                </p>
                                            </div>
                                        </div>
                                    </Link>
                                );
                            })}
                        </div>
                    ) : (
                        <div className="text-center py-12 text-gray-500">
                            No templates found in this category.
                        </div>
                    )}

                    {/* Pagination */}
                    {totalPages > 1 && (
                        <div className="flex items-center justify-center gap-2 mt-12">
                            <button
                                onClick={() => handlePageChange(currentPage - 1)}
                                disabled={currentPage === 1}
                                className="w-10 h-10 flex items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                                aria-label="Previous page"
                            >
                                <ChevronLeft className="w-5 h-5" />
                            </button>

                            {getPageNumbers().map((page, index) => (
                                typeof page === 'number' ? (
                                    <button
                                        key={index}
                                        onClick={() => handlePageChange(page)}
                                        className={`w-10 h-10 flex items-center justify-center rounded-lg text-sm font-medium transition-colors ${currentPage === page
                                            ? 'bg-blue-600 text-white'
                                            : 'border border-gray-200 bg-white text-gray-700 hover:bg-gray-50'
                                            }`}
                                    >
                                        {page}
                                    </button>
                                ) : (
                                    <span key={index} className="w-10 h-10 flex items-center justify-center text-gray-400">
                                        {page}
                                    </span>
                                )
                            ))}

                            <button
                                onClick={() => handlePageChange(currentPage + 1)}
                                disabled={currentPage === totalPages}
                                className="w-10 h-10 flex items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                                aria-label="Next page"
                            >
                                <ChevronRight className="w-5 h-5" />
                            </button>
                        </div>
                    )}
                </div>

                {/* FAQ Section - using unified FAQSection component */}
                <div className="mt-16">
                    <FAQSection
                        items={templatesFAQs}
                    />
                </div>
            </PageLayout>
        </>
    );
}
